### ISSUE TITLE
Specificity of search_x()

### ISSUE THREAD

**Issue by ShuqingR** [fwimp/ohvbd#2]
When running the given example:
`df <- search_vt("Aedes aegypti") %>%
  get_vt_byid() %>%
  extract_vt_data(
    cols = c("Interactor1Genus", "Interactor1Species", "Latitude", "Longitude"),
    returnunique = TRUE
  )
df`
The returned data will contain multiple species, not only Aedes eagypti.
Is there anyway to specify a value for a column? 
So the data can be filtered before downloading.

**Comment by fwimp** [comment]
So there is another search function called [`search_vt_smart()`](https://fwimp.github.io/ohvbd/reference/search_vt_smart.html) which allows you to construct a more specific column-based request. It does not presently handle multiple column queries, however you can either leverage a dplyr-based filter afterwards, or rely on the relatively slim chance of species name collisions to get a pretty good search.

So I would approach this using the following code:

``` r
df <- search_vt_smart("Interactor1Species", "eq", "aegypti") %>%
    get_vt_byid() %>%
    extract_vt_data(cols = c(
        "Interactor1Genus",
        "Interactor1Species",
        "Latitude",
        "Longitude"), returnunique=TRUE)
```

If you wanted to make sure that the only included rows are of the Aedes genus, you could then filter using dplyr:

``` r
library(dplyr)
df <- df %>% filter(Interactor1Genus == "Aedes")
```
